p1: p1.c
		gcc -Wall -ansi -pedantic p1.c -o p1

p2: p2.c
		gcc -Wall -ansi -pedantic p2.c -o p2

p3: p3.c
		gcc -Wall -ansi -pedantic p3.c -o p3

p4: p4.c
		gcc -Wall -ansi -pedantic p4.c -o p4

p5: p5.c
		gcc -Wall -ansi -pedantic p5.c -o p5

p6: p6.c
		gcc -Wall -ansi -pedantic p6.c -o p6

p7: p7.c
		gcc -Wall -ansi -pedantic p7.c -o p7

p8: p8.c
		gcc -Wall -ansi -pedantic p8.c -o p8

p9: p9.c
		gcc -Wall -ansi -pedantic p9.c -o p9

all:
		gcc -Wall -ansi -pedantic p1.c -o p1
		gcc -Wall -ansi -pedantic p2.c -o p2
		gcc -Wall -ansi -pedantic p3.c -o p3
		gcc -Wall -ansi -pedantic p4.c -o p4
		gcc -Wall -ansi -pedantic p5.c -o p5
		gcc -Wall -ansi -pedantic p6.c -o p6
		gcc -Wall -ansi -pedantic p7.c -o p7
		gcc -Wall -ansi -pedantic p8.c -o p8
		gcc -Wall -ansi -pedantic p9.c -o p9
