# all:
# 	gcc -Xpreprocessor -fopenmp -lomp p2.c -o p2
# 	gcc -Xpreprocessor -fopenmp -lomp p3.c -o p3
# 	gcc -Xpreprocessor -fopenmp -lomp p4.c -o p4
# 	gcc -Xpreprocessor -fopenmp -lomp p5.c -o p5
# 	gcc -Xpreprocessor -fopenmp -lomp p6.c -o p6
# 	gcc -Xpreprocessor -fopenmp -lomp p7.c -o p7
# 	gcc -Xpreprocessor -fopenmp -lomp p8.c -o p8

all:
	gcc -Wall -O2 -fopenmp -lm p2.c -o p2
	gcc -Wall -O2 -fopenmp -lm p3.c -o p3
	gcc -Wall -O2 -fopenmp -lm p4.c -o p4
	gcc -Wall -O2 -fopenmp -lm p5.c -o p5
	gcc -Wall -O2 -fopenmp -lm p6.c -o p6
	gcc -Wall -O2 -fopenmp -lm p7.c -o p7
	gcc -Wall -O2 -fopenmp -lm p8.c -o p8
